### ISSUE TITLE
Error "bundle: command not found"

### ISSUE THREAD

**Issue by krichly** [windy/mina-ng-puma#1]
After replacing the mina-puma gem with the mina-ng-puma gem, I get the flowing error during the phased-restart phase in the deployment: 

`Restart Puma -- phased...
bash: line 178: bundle: command not found
Waiting phased-restart finish( default: 120 seconds)...
       bash: line 198: bundle: command not found
       bash: line 199: bundle: command not found
       bash: line 198: bundle: command not found
       bash: line 199: bundle: command not found
       bash: line 198: bundle: command not found
       bash: line 199: bundle: command not found
       bash: line 198: bundle: command not found
       bash: line 199: bundle: command not found
       bash: line 198: bundle: command not found
       bash: line 199: bundle: command not found
       bash: line 198: bundle: command not found
       bash: line 199: bundle: command not found`

Bundle is installed and the bundle:install step in the mina deployment finishes with Bundle complete!   

Bundle version: 1.17.3

**Comment by windy** [comment]
Hi,  Did you add 

```
task :remote_environment do
  invoke :'rbenv:load'
end
```

to your deploy.rb ?

**Comment by krichly** [comment]
Hi, I am using rvm, but my deploy.rb includes the following task

```
task :remote_environment do
    invoke :'rvm:use', 'ruby-2.4.1@default'
end
```

**Comment by windy** [comment]
@krichly not sure why,  mina-ng-puma only add a bundle_prefix flag just like mina-puma doing, see puma/tasks for a detail.

I think maybe your bashrc config miss some script for rvm ?

**Comment by windy** [comment]
@krichly hi, how about this?

**Comment by krichly** [comment]
Hi @windy, thanks for your response. We had several modifications to our infrastructure, and now everything is working, but I have no idea which changes made the difference at the end.
