### ISSUE TITLE
Should I switch from mina-puma to mina-ng-puma?

### ISSUE THREAD

**Issue by jmuheim** [windy/mina-ng-puma#3]
Hello

I finally managed to make mina-puma work, and then I stumble over mina-ng-puma.

I have issued a comment on mina-puma, and as I don't get an answer there, I can add the same question here:

> I find the README could be a bit more exhaustive (e.g. I did not find anything about puma_port setting until I dug into the code itself).
>
> If I add details to the README, would this PR possibly be merged?

See https://github.com/untitledkingdom/mina-puma/pull/20#issuecomment-537420957

Thank you.

**Comment by windy** [comment]
@jmuheim  Glad to hear it.  And any improvement is welcome.

**Comment by jmuheim** [comment]
Thanks for your reaction. There's one big question left for me regarding the deployment process, maybe you have an opinion/idea about that:

I asked on StackOverflow: https://stackoverflow.com/questions/58372477/deployment-of-a-rails-app-how-should-the-db-be-loaded-and-filled-during-the-ver

**Comment by windy** [comment]
see our example:  https://github.com/dao42/rails-template/blob/master/files/config/deploy.rb#L102
